name: sembast_sqflite_test
description: sembast sqflite test
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sembast_sqflite: '>=0.1.0 <2.0.0'

dev_dependencies:
  sqflite_common_ffi: '>=1.0.0 <3.0.0'
  sqflite: '>=1.3.0+2 <3.0.0'
  test:
  process_run: '>=0.10.3'
  pedantic: '>=1.8.0'
  sembast_test:
    git:
      url: git://github.com/tekartik/sembast.dart
      path: sembast_test
      ref: develop
    version: '>=0.1.3'
  build_runner: '>=0.9.0'
  build_web_compilers: '>=0.4.0+4'
  build_test: '>=0.10.2+5'

dependency_overrides:
  sembast_sqflite:
    path: ../sembast_sqflite