name: sembast_sqflite
description: sembast NoSQL database support on top of sqflite, cross process safe database.
homepage: https://github.com/tekartik/sembast_sqflite/tree/master/sembast_sqflite
version: 2.0.1

environment:
  sdk: '>=3.0.0 <3.6.0'

dependencies:
  sembast:
    git:
      url: https://github.com/i-atros/sembast.dart.git
      path: sembast
      ref: upgrade-dart-sdk
  sqflite_common: '>=2.0.0 <4.0.0'
  meta: '>=1.3.0 <3.0.0'
  collection: '>=1.15.0 <3.0.0'

dev_dependencies:
  sqflite_common_ffi: '>=2.0.0'
  test: '>=1.16.2'
  process_run: '>=0.12.0'
  pedantic: '>=1.10.0'
  pub_semver: '>=2.0.0'
  yaml: '>=3.0.0'
